import "./globals.css";
import { Playfair_Display } from "next/font/google";
import { Tenor_Sans } from "next/font/google";
import { Bodoni_Moda } from "next/font/google";
import { Outfit } from "next/font/google";
import LayoutClient from "./LayoutClient";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-playfair",
});

const tenor = Tenor_Sans({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-tenor",
});

const bodoni = Bodoni_Moda({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${tenor.className} min-h-screen flex flex-col`}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
