"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _home_page from './home-page.bones.json'
import _main_div from './main-div.bones.json'

registerBones({
  "home-page": _home_page,
  "main-div": _main_div,
})
